baseURL = "https://arusank.com"
title = "Bunny's blog"
theme = "m10c"
paginate = 10
publishDir = "../docs/"

[params]
  author = "Bunny & Bunny"
  description = "Always high on happiness"
  [[params.social]]
    name = "github"
    url = "https://github.com/mkmayank"
  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/foodiescritiques"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
